version: "3.9"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: es01
    restart: always
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ELASTIC_USER=${ES_USER}"
      - "ELASTIC_PASSWORD=${ES_PWD}"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    networks:
      - docker_tripper

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.2
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://${ES_HOST}:9200
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - es01
    networks:
      - docker_tripper

volumes:
  elastic:
    driver: local

networks:
  docker_tripper:
    external: true
